### ISSUE TITLE
Hope to access the integrated data

### ISSUE THREAD

**Issue by WeiCSong** [fhermans27/scRNAseq-tooth-atlas#1]
Hi Hermans,
Just read your excellent paper and I wonder whether you could share the integrated data (R object "integrated" for human and mouse), so that further analysis could be applied based on your uniform cell type annotation? Thank you very much for your help.

**Comment by fhermans27** [comment]
Dear Weichen, 
thanks for the kind words. I would be happy to share the objects with you. Feel free to drop me an email at florian.hermans@uhasselt.be so I can transfer them to you. 
Cheers,
Florian

**Comment by WeiCSong** [comment]
Thanks! could you transfer to song628196@gmail.com? Seems that my email was blockedby your email.
